import java.net.Socket
import java.nio.charset.StandardCharsets

fun main(args: Array<String>) {
    val socket1 = Socket("localhost", 10301)
    val input1 = socket1.getOutputStream()

    val long = ("Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer messageHello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message " +
                "Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer messageHello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message " +
                "Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer messageHello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message " +
                "Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer messageHello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message " +
                "Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer messageHello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message " +
                "Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer messageHello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message Hello ServerAcceptor this is a longer message\n").toByteArray(StandardCharsets.UTF_8)

    input1.write(long)

    val shortMessage = ("12345678-12345678\n").toByteArray(StandardCharsets.UTF_8)
    val socket2 = Socket("localhost", 10301)
    val input2 = socket2.getOutputStream()
    input2.write(shortMessage)
}